### ISSUE TITLE
Merge Application & Viewer tabs

### ISSUE THREAD

**Issue by qqnluaq** [bcgov/smk-cli#14]
Proposal that the application & viewer tabs be merged. Not enough information on either of them, and easy to combine them.
New tab would called 'Viewer'.

**Comment by NicoledeGreef** [comment]
good suggestion - thanks.  for now we've confirmed that leaflet is the only map viewer type.

Base Map choices _could_ be in a drop down list to minimize screen real estate if level if effort is low to implement.

**Comment by qqnluaq** [comment]
1.0.0-beta.5
