### ISSUE TITLE
Add Vector Data set to Catalog - Title field obscured

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#17]
Noticed that when a geoJSON URL is pasted in, the Title becomes obscured by the Save and View buttons.

![image](https://user-images.githubusercontent.com/26335003/91781305-d5adde80-ebae-11ea-80f0-6067998d21b0.png)

Perhaps a little scrollbar is necessary to account for the increase in lines?  I was able to type in Title only after added a URL.  I could tab to the Title but only because i knew it was there and I was trying to get to it.  Cannot save the layer without putting in both the URL and a Title.

**Comment by qqnluaq** [comment]
1.0.0-beta.5
