### ISSUE TITLE
Add Vector Dataset URL to Catalog - returning the geoJSON

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#18]
beta3

I added a URL:

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_FRPH_TOURISM_SVW&outputFormat=application/json&srsname=EPSG:4326

saved it as tourism.

went to another part of the Editor, cameback to it and found that the URL was gone but it took a while to open and the actualy returned geoJSON was there (very long scroll):

![image](https://user-images.githubusercontent.com/26335003/91781678-b8c5db00-ebaf-11ea-933c-7bd0dbbb0c5e.png)

**Comment by qqnluaq** [comment]
Can you reproduce this? I need more detailed steps..

**Comment by NicoledeGreef** [comment]
I have not been able to reproduce it today.  Can icebox this unless it shows up again.
