### ISSUE TITLE
unable to rename or delete Vector Layers?

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#21]
beta3

Seven WFS based vector layers were added to a map.  Due to the Title field being obscured when the long URL is pasted in, I made typos in the Title.  I cannot seem to edit the Title (rename the layers) or delete them and start anew.

![image](https://user-images.githubusercontent.com/26335003/92208946-03aa5180-ee41-11ea-98c2-3a914fc99c0e.png)

**Comment by qqnluaq** [comment]
see #22

**Comment by qqnluaq** [comment]
i will implement editing and deleting of items in the vector layer catalog.

**Comment by qqnluaq** [comment]
1.0.0-beta.6

Click on layer in catalog to see remove icon (only if layer is not in app)
Hit Enter while layer selected to edit title

**Comment by NicoledeGreef** [comment]
i could get the layer to delete (via the red icon) but i was not successful in renaming the layer in the vector list by hitting enter.  i used Chrome.

**Comment by qqnluaq** [comment]
Because of Reasons, hitting Enter to edit the layer name only works on a Mac. However, other ways to trigger editing also work, either hitting F2, or holding SHIFT and clicking on the name. I think this can be improved, but I think we should make it a post-release fix

**Comment by NicoledeGreef** [comment]
figured it might be a Mac thing.  agree- post-launch.
