### ISSUE TITLE
Identify of vector data showing unexpected layer name

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#22]
beta3

When identifying on vector data the title returned seems to be the one I cannot edit, not the nice name I gave it when I added it to the application.

In the example below, "Early ChildhoodWorkBC Centres" is a typo; I expected "WorkBC Centres" to be the layer name displayed as it is in the Layer List.

![image](https://user-images.githubusercontent.com/26335003/92209400-c72b2580-ee41-11ea-9e86-42e6130d20a9.png)

![image](https://user-images.githubusercontent.com/26335003/92209457-e4f88a80-ee41-11ea-87bf-3fcf37407b1f.png)

**Comment by NicoledeGreef** [comment]
ok - i would expect then that "WorkBC Centres" shows up in the Identify Features panel, not the dev name "Early ChildhoodWorkBC Centres".

**Comment by NicoledeGreef** [comment]
i will try to come up with some instructional text for the Vector Layer Management screen so that users can understand that the initial import "title" shown on the left hand side is for dev purposes (recommended to keep it short, etc.) and that the right hand side are actually the layer configuration, nice names, etc.

**Comment by qqnluaq** [comment]
1.0.0-beta.5

**Comment by NicoledeGreef** [comment]
I still see the "layer catalog name" (Health) showing up in the identify results when I would expect the nice name as configured in the app (Health Professionals - Francophone):

![image](https://user-images.githubusercontent.com/26335003/92559369-557a1f80-f225-11ea-9f30-3e93a5bcacaa.png)

![image](https://user-images.githubusercontent.com/26335003/92559330-3d0a0500-f225-11ea-91c8-511c30f0068b.png)
