### ISSUE TITLE
Vector data not allowing editing of Attribute visibility, nice names

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#23]
beta3

Several vector layer added: 
http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_SCHOOLS_K_TO_12_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_FRPH_HLTH_PROFESSIONAL_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_FRPH_SERVICE_DIRECTORY_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_FRPH_TOURISM_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_FRPH_EARLY_CHILDCARE_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_EMPL_SRVCS_OFFICES_SVW&outputFormat=application/json&srsname=EPSG:4326

The SMK Editor interface is not loading the attributes so that they can be set to not display when identifies occur.  Choose title attribute and geometry attribute is also failing to populate with the names of attributes:

![image](https://user-images.githubusercontent.com/26335003/92211360-30606800-ee45-11ea-9792-a2def05dc7f8.png)

Not sure if related but all of these layers are  based on the 'Geographic Site Registry' model and have a high number of attributes.

**Comment by qqnluaq** [comment]
1.0.0-beta.5

**Comment by NicoledeGreef** [comment]
I upgraded to beta5 and opened the site i've been working on since beta2 but unfortunately the Attributes are not populating (same as screen shot above).

**Comment by qqnluaq** [comment]
The attributes are populated when the layer is added to the vector catalog. So you will need to add the external url to the catalog again. The newly added catalog item will have the attributes, so you will have to add that item to your app (and remove the previous version of that layer). 
Sorry its a bit tedious.

**Comment by NicoledeGreef** [comment]
Thanks for the info.  I will try that.

**Comment by NicoledeGreef** [comment]
closing this ticket as things are working.  have added ticket 32
