### ISSUE TITLE
Vector WFS data markers not showing in the Legend

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#24]
beta3

Several vector layer added:
http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_SCHOOLS_K_TO_12_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_FRPH_HLTH_PROFESSIONAL_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_FRPH_SERVICE_DIRECTORY_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_FRPH_TOURISM_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_FRPH_EARLY_CHILDCARE_SVW&outputFormat=application/json&srsname=EPSG:4326

http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_EMPL_SRVCS_OFFICES_SVW&outputFormat=application/json&srsname=EPSG:4326

When the site is reviewed via the "View" button in the SMK Editor, the markers are not visible in the legend.  The markers are all imported PNGs in this case.

![image](https://user-images.githubusercontent.com/26335003/92310628-17e76f00-ef65-11ea-872d-c629cab20d98.png)

**Comment by qqnluaq** [comment]
1.0.0-beta.6

fixed many bugs with vector layer styling. Added checkboxes to control how legend is displayed, including the legend title.

**Comment by NicoledeGreef** [comment]
verified that the legend is now configurable. 

suggest placing the icons underneath each layer instead of to the rightas in the following screenshot:
![image](https://user-images.githubusercontent.com/26335003/93148707-5ee20c80-f6a9-11ea-9378-0ef9cdb1192f.png)

**Comment by qqnluaq** [comment]
needs fix in smk: https://github.com/bcgov/smk/issues/57

**Comment by qqnluaq** [comment]
smk-cli@1.0.0-beta.7 fixed formatting
