### ISSUE TITLE
Special characters in Identify results

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#25]
beta3

Working with francophone-related data I noticed that special character handling might need attention at this point in time.  In this case it is being accessed via WFS:

![image](https://user-images.githubusercontent.com/26335003/92310673-80365080-ef65-11ea-9288-dfd6233448c7.png)

See same data in iMapBC (accessed via MPCM):
![image](https://user-images.githubusercontent.com/26335003/92310723-e622d800-ef65-11ea-9524-42f33ff432b8.png)

**Comment by qqnluaq** [comment]
What browser/OS are you seeing this behaviour? On my machine (Chrome/Mac), it works correctly.

**Comment by NicoledeGreef** [comment]
i just reviewed in beta5 and it's not happening :)
