### ISSUE TITLE
Vector layers in app should always appear in catalog

### ISSUE THREAD

**Issue by qqnluaq** [bcgov/smk-cli#30]
A vector layer in an app may not have been added to the app via the editor, so it may not appear in the vector catalog. The editor should check for this case, and add an entry to the catalog for the layer.

Otherwise, if the layer is removed from the app, there is no way to get it back, other than recreating it.

**Comment by NicoledeGreef** [comment]
level of effort (Small, Medium, Large)?

**Comment by qqnluaq** [comment]
small

**Comment by qqnluaq** [comment]
smk-cli@1.0.0-beta.7
