### ISSUE TITLE
configuration version

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#31]
In the Application panel of the Simple Map Kit Editor there is a "Configuration Version" value.  In my case I had created a site under beta2 but essentially upgraded it everytime i saved it on a new beta version (now beta5).  Should that value be updated, or maybe we call it "Initial Configuration Version" and list a Current Configuration Version" as well?  Not sure of the purpose in listing it for end users; what was the intention of including it?

![image](https://user-images.githubusercontent.com/26335003/92557912-3b8b0d80-f222-11ea-9deb-02c7c670fd0f.png)

**Comment by qqnluaq** [comment]
1.0.0-beta.6

removed
