### ISSUE TITLE
UI Paint Point: Renaming Attributes

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#32]
When editing the attribute "nice names" in the SMK Editor, I noticed that every time i would scroll down the list to an attribute and then click the attribute name , the attribute panel expanded but focus was set at the bottom of the expanded attribute panel so that i then had to scroll up a little bit to actually edit the attribute nice name.  If you have to edit, for example, 10 attributes in a list of 24, the additional scrolling up takes some can add up in terms of extra time/effort.

**Comment by qqnluaq** [comment]
1.0.0-beta.6

reworked attribute list. shows name and title and ordering controls in header. only title is editable.
