### ISSUE TITLE
defining queries on vector data

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#35]
<= beta6

In the francophonie site which has been draft on beta2-beta6 and contains 100% vector data sources, a configured query on the school layers is not returning results whether it is AND or OR as the operand.

![image](https://user-images.githubusercontent.com/26335003/94635599-dc9c3f80-0287-11eb-8c8a-de5108b5edcf.png)

You can see this site deployed at: http://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/

The Search icon is a shortcut icon on the bottom right side for now.  Search attempts don't generate results where there should be results returned.

![image](https://user-images.githubusercontent.com/26335003/94635512-a8288380-0287-11eb-90ce-ee74f55c2791.png)

**Comment by qqnluaq** [comment]
smk-cli@1.0.0-beta.7

note, that the select parameter type is basically non-functional, as theres no way to populate the drop down list. Fortunately, this type is not very useful.
