### ISSUE TITLE
find nearby/search radius tool definition

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#36]
beta6

currently pixels and meters are the values available for the search radius tool.  can we add kilometers as well?  For social sector data sites i think that would be more ideal.

![image](https://user-images.githubusercontent.com/26335003/93505770-240ded80-f8d0-11ea-9e18-5d004f50694f.png)

**Comment by qqnluaq** [comment]
needs work in smk: https://github.com/bcgov/smk/issues/58

**Comment by qqnluaq** [comment]
smk-cli@1.0.0-beta.7

also requires an updated smk: 1.0.0-beta.3
