### ISSUE TITLE
unsupported character

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#37]
beta6

a character is showing up as a box.  i suspect it is a double-dash?
![image](https://user-images.githubusercontent.com/26335003/93506874-be226580-f8d1-11ea-8914-63629ad1d054.png)

**Comment by qqnluaq** [comment]
it appears to be garbage data. the bytes in question are 0xc2 0x96 which don't decode to anything in UTF8 as far as i can tell.

**Comment by NicoledeGreef** [comment]
have asked DAs to look into this record.

**Comment by NicoledeGreef** [comment]
confirmed to be garbage data; Brad found a number of instances of this in the Francophone data sets.  he will take it to his Chapter for investigation/resolution.
