### ISSUE TITLE
bespoke tool truncating content upon review of the map

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#40]
beta7

Using the bespoke content editor is pretty smooth.  When reviewing the map as configured with a bespoke panel I noticed a double scroll bar and I am not able to reach the bottom of the content.

![image](https://user-images.githubusercontent.com/26335003/93646259-ba1e4280-f9ba-11ea-81bb-d524836b128d.png)

**Comment by qqnluaq** [comment]
that's not a double scrollbar, its just a little arrow icon. It is misleading though, but removing it is a change to smk: https://github.com/bcgov/smk/issues/60

**Comment by NicoledeGreef** [comment]
I agree it's a bit confusing.  Seen here as well:
![image](https://user-images.githubusercontent.com/26335003/93649930-00c36b00-f9c2-11ea-97ea-53285d18dbeb.png)

Closing this comment and will prioritize https://github.com/bcgov/smk/issues/60
