### ISSUE TITLE
bespoke content editor very small

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#41]
beta7

just an observation as I was trying to edit content in a bespoke tool, the height of the editor could be bigger to make it easier.

![image](https://user-images.githubusercontent.com/26335003/93646524-416bb600-f9bb-11ea-9f6b-a298f125c758.png)

**Comment by qqnluaq** [comment]
OS, browser?

**Comment by qqnluaq** [comment]
1.0.0-beta.8.

**Comment by NicoledeGreef** [comment]
Windows 10 , Chrome
