### ISSUE TITLE
UI control for showCoverageOnHover (for clustered data)

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#63]
Related to  https://github.com/bcgov/smk/issues/103/

It would be beneficial for SMK-CLI (SMK Editor) users to be able to toggle on showCoverageOnHover for a given vector layer. 
 Value should be false by default, please.

**Comment by michaelpnelson** [comment]
This issue was addressed by pull request https://github.com/bcgov/smk-cli/pull/75 and merged to master.
