### ISSUE TITLE
Manage Vector Layers - Not working

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/smk-cli#66]
When trying to work with some custom layers I am running into the following issue:

* click on Layers-> Manage Vector Layers 

get an error message saying the -smk-catalog.json file does not exist. 

Then when I try to import a vector layer:
* Import Vector Layer in Catalog-> Choose file type-> CSV ->specify the lat/long columns

After that is complete the layer does not show up in the list of vector layers.  I think what is suppose to happen is the csv gets converted to geojson, and then you should be able to add that layer. Anyways after clicking through the section where you define the columns the layer never shows up anywhere.

I was eventually able to add a geojson object using the gui.  I think the problem might be specific to layers that need to be transformed before they can be used.

**Comment by dgboss** [comment]
@franTarkenton I'm able to add a csv file with point features using the GUI and then I am able to add it to the layers I want in my map. Do you have a specific sample file you could share that demonstrates the issue? Thanks!

**Comment by michaelpnelson** [comment]
Hi @franTarkenton. I'm checking in on the CSV transformation problem you were experiencing. Are you still seeing the issue? If you are, could you send us a sample file we could use to replicate the issue? Thanks!

**Comment by michaelpnelson** [comment]
As part of revisiting older issues, we're closing this one. If the CSV issue is seen again, we can create a new issue.
