### ISSUE TITLE
Hide internal/secured MPCM layers in the smk-cli editor

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#70]
The smk-cli editor app should only display non-secured DataBC (MPCM) layers; it currently displays all layers

**Comment by michaelpnelson** [comment]
This was addressed in pull request https://github.com/bcgov/smk-cli/pull/71. 

Test Steps:
- Navigate to Layers/Manage DataBC Layers
- Confirm that one or more layers that are not in the MPCM_ALL_PUB workspace are not included in the catalog’s layers (for example, Geodetic Survey/High Precision Survey Monuments: id 1890, workspace MPCM_ALL_GOV)
- Confirm that layers can be selected and viewed as before
