### ISSUE TITLE
ability to turn on labels on DataBC (MPCM) layers

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#76]
Question was posed on yammer:

https://web.yammer.com/main/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMTA0MjA4NzY2NzY5NTYxNiJ9

Is it possible to turn on labels for added DataBC layers?

**Comment by michaelpnelson** [comment]
When labeling info exists for an ESRI dynamic layer, it can now be toggled on and off by a new "Show labels" check box in SMK-CLI. This was implemented in https://github.com/bcgov/smk-cli/pull/94.

**Comment by michaelpnelson** [comment]
As mentioned, we added the ability to show labels when labeling info exists. 

It's also possible to fine-tune the content and styling of labels by editing **smk-config.json**. Each DataBC layer in the **layers** property has a **dynamicLayers** property. This includes a **drawingInfo** property which defines the appearance of the layer on the map. Label content and style can be updated by editing its **labelingInfo** property. For more information, see [drawingInfo documentation](https://developers.arcgis.com/web-map-specification/objects/drawingInfo).
