### ISSUE TITLE
Left hand panel text update

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#9]
Welcome to the Simple Map Kit Editor

Use the Editor to modify your application's map configuration and click **View** at any time to review your changes, and **Save** at any time to capture them.

![image](https://user-images.githubusercontent.com/26335003/91479434-44f59c80-e856-11ea-8117-70fcd860de24.png)

**Comment by qqnluaq** [comment]
1.0.0-beta.5

**Comment by NicoledeGreef** [comment]
this is minor but can you please bold "Save" and "View" in the text?

**Comment by qqnluaq** [comment]
1.0.0-beta.6
